# packages in environment at /Users/ras/anaconda3/envs/mplh:
#
# Name                    Version                   Build  Channel
appnope                   0.1.0                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.1.4                    pypi_0    pypi
brewer2mpl                1.4.1                    pypi_0    pypi
ca-certificates           2020.1.1                      0  
certifi                   2019.11.28               py38_1  
colorspacious             1.1.2                    pypi_0    pypi
cycler                    0.10.0                   py38_0  
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
freetype                  2.9.1                hb4e5f40_0  
intel-openmp              2019.4                      233  
ipykernel                 5.2.0                    pypi_0    pypi
ipython                   7.13.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
jedi                      0.16.0                   pypi_0    pypi
jinja2                    2.11.1                   pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.2                    pypi_0    pypi
jupyter-console           6.1.0                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
kiwisolver                1.0.1            py38h0a44026_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libpng                    1.6.37               ha441bb4_0  
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.1.3                    py38_0  
matplotlib-base           3.1.3            py38h9aa3819_0  
mistune                   0.8.4                    pypi_0    pypi
mkl                       2019.4                      233  
mkl-service               2.3.0            py38hfbe908c_0  
mkl_fft                   1.0.15           py38h5e564d8_0  
mkl_random                1.1.0            py38h6440ff4_0  
mplh                      0.1.0                     dev_0    <develop>
nbconvert                 5.6.1                    pypi_0    pypi
nbformat                  5.0.5                    pypi_0    pypi
ncurses                   6.2                  h0a44026_0  
notebook                  6.0.3                    pypi_0    pypi
numpy                     1.18.1           py38h7241aed_0  
numpy-base                1.18.1           py38h6575580_1  
openssl                   1.1.1f               h1de35cc_0  
pandas                    1.0.3            py38h6c726b0_0  
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.6.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       20.0.2                   py38_1  
prometheus-client         0.7.1                    pypi_0    pypi
prompt-toolkit            3.0.5                    pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pygments                  2.6.1                    pypi_0    pypi
pyparsing                 2.4.6                      py_0  
pyrsistent                0.16.0                   pypi_0    pypi
python                    3.8.2                hc70fcce_0  
python-dateutil           2.8.1                      py_0  
pytz                      2019.3                     py_0  
pyzmq                     19.0.0                   pypi_0    pypi
qtconsole                 4.7.2                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  8.0                  h1de35cc_0  
scipy                     1.4.1            py38h44e99c9_0  
seaborn                   0.10.0                     py_0  
send2trash                1.5.0                    pypi_0    pypi
setuptools                46.1.3                   py38_0  
six                       1.14.0                   py38_0  
sqlite                    3.31.1               ha441bb4_0  
terminado                 0.8.3                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
tk                        8.6.8                ha441bb4_0  
tornado                   6.0.4            py38h1de35cc_1  
traitlets                 4.3.3                    pypi_0    pypi
wcwidth                   0.1.9                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.34.2                   py38_0  
widgetsnbextension        3.5.1                    pypi_0    pypi
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               h1de35cc_3  
